# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/urbai/projects/cppokemon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/urbai/projects/cppokemon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/urbai/projects/cppokemon/CMakeFiles /home/urbai/projects/cppokemon//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/urbai/projects/cppokemon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cppokemon

# Build rule for target.
cppokemon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cppokemon
.PHONY : cppokemon

# fast build rule for target.
cppokemon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppokemon.dir/build.make CMakeFiles/cppokemon.dir/build
.PHONY : cppokemon/fast

libs/pokemon/src/pokemon.o: libs/pokemon/src/pokemon.cpp.o
.PHONY : libs/pokemon/src/pokemon.o

# target to build an object file
libs/pokemon/src/pokemon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppokemon.dir/build.make CMakeFiles/cppokemon.dir/libs/pokemon/src/pokemon.cpp.o
.PHONY : libs/pokemon/src/pokemon.cpp.o

libs/pokemon/src/pokemon.i: libs/pokemon/src/pokemon.cpp.i
.PHONY : libs/pokemon/src/pokemon.i

# target to preprocess a source file
libs/pokemon/src/pokemon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppokemon.dir/build.make CMakeFiles/cppokemon.dir/libs/pokemon/src/pokemon.cpp.i
.PHONY : libs/pokemon/src/pokemon.cpp.i

libs/pokemon/src/pokemon.s: libs/pokemon/src/pokemon.cpp.s
.PHONY : libs/pokemon/src/pokemon.s

# target to generate assembly for a file
libs/pokemon/src/pokemon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppokemon.dir/build.make CMakeFiles/cppokemon.dir/libs/pokemon/src/pokemon.cpp.s
.PHONY : libs/pokemon/src/pokemon.cpp.s

libs/utils/src/utils.o: libs/utils/src/utils.cpp.o
.PHONY : libs/utils/src/utils.o

# target to build an object file
libs/utils/src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppokemon.dir/build.make CMakeFiles/cppokemon.dir/libs/utils/src/utils.cpp.o
.PHONY : libs/utils/src/utils.cpp.o

libs/utils/src/utils.i: libs/utils/src/utils.cpp.i
.PHONY : libs/utils/src/utils.i

# target to preprocess a source file
libs/utils/src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppokemon.dir/build.make CMakeFiles/cppokemon.dir/libs/utils/src/utils.cpp.i
.PHONY : libs/utils/src/utils.cpp.i

libs/utils/src/utils.s: libs/utils/src/utils.cpp.s
.PHONY : libs/utils/src/utils.s

# target to generate assembly for a file
libs/utils/src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppokemon.dir/build.make CMakeFiles/cppokemon.dir/libs/utils/src/utils.cpp.s
.PHONY : libs/utils/src/utils.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppokemon.dir/build.make CMakeFiles/cppokemon.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppokemon.dir/build.make CMakeFiles/cppokemon.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppokemon.dir/build.make CMakeFiles/cppokemon.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cppokemon"
	@echo "... libs/pokemon/src/pokemon.o"
	@echo "... libs/pokemon/src/pokemon.i"
	@echo "... libs/pokemon/src/pokemon.s"
	@echo "... libs/utils/src/utils.o"
	@echo "... libs/utils/src/utils.i"
	@echo "... libs/utils/src/utils.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

